version: "3"
services:
    azure_function:      
      image: "ebarrioscode/functionexample"
      build: 
        context: .
        dockerfile: Dockerfile        
      ports:
        - "8080:80"
      environment: 
        SqlConnectionString: "<connection-string>"    
        
